### ISSUE TITLE
Specifying FHIR resources for Data Element/Input Option combinations

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#101]
Given the two options below, is one or the other preferable for the tooling to map FHIR resources to data element/input option combinations? Are both viable options? 

**Option 1**: (where each input option has a resource to which it will be mapped, and the data element is mapped to its own resource)

Master ID | Master Data Element Label | Master   Data Type | Data   Element Parent for Input Options | HL7   FHIR R4 - Resource | HL7   FHIR R4 - Base Profile | HL7   FHIR R4 - Version Number
-- | -- | -- | -- | -- | -- | --
1433 | Breast Exam | Data   Element |   | Procedure.code | FHIR | 4.0.1
1434 | Not   done | Input   Option | Breast   Exam | Procedure.status | FHIR | 4.0.1
1435 | Normal | Input   Option | Breast   Exam | Procedure.outcome | FHIR | 4.0.1
1436 | Abnormal | Input   Option | Breast   Exam | Procedure.outcome | FHIR | 4.0.1

__________________________________________________________________________________________________

**Option 2**: (where all input options are mapped to the same FHIR resource)

Master   ID | Master   Data Element Label | Master   Data Type | Data   Element Parent for Input Options | HL7   FHIR R4 - Resource | HL7   FHIR R4 - Base Profile | HL7   FHIR R4 - Version Number
-- | -- | -- | -- | -- | -- | --
1882 | STI risk   assessment factors | Data   Element |   | Observation.code | FHIR | 4.0.1
1883 | Sex   worker | Input   Option | STI   risk assessment factors |   |   |  
1884 | Sex   with HIV+ person | Input   Option | STI   risk assessment factors |   |   |  
1885 | Referral   for STI screening | Input   Option | STI   risk assessment factors |   |   |  
1886 | Casual   sexual partner | Input   Option | STI   risk assessment factors |   |   |  
1887 | No   condom use during sex | Input   Option | STI   risk assessment factors |   |   |  
1888 | Patient   with multiple sexual partners | Input   Option | STI   risk assessment factors |   |   |  

cc: @jennifershivers

**Comment by brynrhodes** [comment]
The first option achieves some economy of expression in the source Data Dictionary, but at the expense of complexity in the tooling and implementation layer. In general, we don't support mapping different input options to different FHIR elements, and doing so would require some significant thought and subsequent effort. Option 2 is what is currently supported by the tooling, but it means that the scenario depicted in Option 1 would actually be two separate questions, one for whether the Breast Exam was done, and one for what the Outcome of that Breast Exam was. One can imagine an implementation that collapsed the question to one, but that would be something the implementation would do, rather than the profiling and data dictionary.

**Comment by jamlung-ri** [comment]
We will update our FHIR mappings so that we will follow Option 2. This may involve creating new data elements so that we are not needing to mix FHIR resources.
