### ISSUE TITLE
Core IG  - items missing 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#104]
1.  Don't see 1236	"Visit Date"
2.  Did not see 1844 | [Administrative Area]  - I removed the brackets in case this was the issue 
3.  Don't see 

1263 | Body height
-- | --
1264 | Body weight

4.  Also missing 

1284 | Never used contraception

**Comment by sliver007** [comment]
1. 1236 "Visit Date" - **This was a bug in the processor code** - Rows with "Data Type" value of DateTime we not resulting in generated Profiles. Fixed in the processor and the profile will be in the next build along with any others that fit the pattern - "Data Type" of DateTime. 

2. 1844 "[Administrative Area]" - This was not being generated because not type as specified in the "Data Type" column. **This should be set to "Text"**. If there is no value in the "Data Type" column, nothing will be generated for the row. 

3. 1263, 1264 "Body height|weight" - **This was a bug in the processor code** - Rows with "Data Type" value of Boolean we not resulting in generated Profiles. Fixed in the processor and the profile will be in the next build along with any others that fit the pattern - "Data Type" of Boolean.  

4. 1284 "Never used contraception" - **This was a bug in the processor code** - Rows with "Data Type" value of Boolean we not resulting in generated Profiles. Fixed in the processor and the profile will be in the next build along with any others that fit the pattern - "Data Type" of Boolean.

**Comment by sliver007** [comment]
New builds of all three IGs are available based on a snapshot taken 2/25/2020 @ 9:22am (MT). "Custom Profile ID" values were removed from this build in order to focus on the issues mentioned above, so no consolidation of Profiles should be expected. 

Core: http://build.fhir.org/ig/who-int/core/branches/WHO_DD/index.html
FP-CDS: http://build.fhir.org/ig/who-int/fp-cds/branches/master/index.html
STI-CDS: http://build.fhir.org/ig/who-int/sti-cds/branches/master/index.html

**Comment by jamlung-ri** [comment]
I updated the spreadsheet column "Data Type" with "Text". 

Just to confirm @sliver007, regarding your comment "If there is no value in the "Data Type" column, nothing will be generated for the row", does every data element throughout the entire spreadsheet need to have a value in the Data Type column to be output into the IG? I see 243 data elements that have a FHIR resource in the HL7 FHIR R4 - Resource column but do not have a Data Type value.

**Comment by sliver007** [comment]
So after sleeping on it and discussing with @brynrhodes this morning...

The "Data Type" column's value was being used in the very beginning because initially it was the most consistent indication of whether or not a profile was required. This has changed quite a bit since then, so we're going to change the Processor code to be driven off of the "Master Data Type" column instead of "Data Type". "Master Data Type" is already being used in the code to some extent so this change will make the code more consistent. So no need to update the "Data Type", I'll make the described change on our end in the tooling.
