### ISSUE TITLE
Mapping value sets using multiple terminology standards

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#19]
I noticed that FHIR allows mapping across multiple terminologies within a single value set. However, I wonder if this is a good strategy for this mapping work. @brynrhodes, do you have any reason for us to avoid this?

Example: [Rows 1372-1379](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us) (Note that some of the input options should reasonably be mapped to only LOINC, while some should only be mapped to SNOMED)

`Reason for stopping contraception method:`
`   - Abstinence`
`   - Side effects of contraception`
`   - Currently pregnant`
`   - Same sex partner`
`   - Other`
`   - Sterile for non-contraceptive reasons`
`   - Seeking pregnancy`

cc: @jennifershivers

**Comment by natschja** [comment]
Just wanted to note that we would likely want to note the mappings to all the relevant terminologies if relevant. so for example, if there's a term in LOINC and in SNOMED - we would want to include both. This is because SNOMED is proprietary (even with the dual market licensing pricing model), so we need to have other free and open source terminologies available if possible. I know this is hard because SNOMED is much more comprehensive that the others, but I think we should include what we can at this point.

**Comment by brynrhodes** [comment]
Within the quality measures development space, it is a best practice to create value sets for each of the different terminologies, and a grouping value set to combine them all. It's more work up front, but it makes management of the value sets easier downstream, especially in cases where different terminologies will apply for different targets.

**Comment by jennifershivers** [comment]
As long as there is a way to handle when a term has an ICD and a SNOMED code, it can be handeled.
