### ISSUE TITLE
Marital Status data element has an input option

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#2]
Issue:  Row 1741 Marital status has one of the input options, "M" and this should be it's own row as the other options are.  https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us/edit#gid=1138104744&fvid=184650586

Recommended action:  Add an appropriate row for the input option of "M"  

Question for WHO:  Is it ok for RI to make theses types of corrections without WHO approval.  We recommend that we track these changes in tickets or another way.  In addition, we are keeping a copy of the DD without modifications.

**Comment by natschja** [comment]
I'm not sure I see the "M" that's being referenced here. I think this could also just be a mistake in the data dictionary that's being finalized. However, once that data dictionary is finalized, I would say it will be ok to make those kind of formatting changes (when it comes to the rows). However, if there are health content changes e.g. changing the data element itself then we would want to discuss first.

**Comment by jamlung-ri** [comment]
Sounds good. This row will end up being removed anyway because marital status is also reflected around ID 1251, but having the precedent is good to know. We can still keep track of formatting-like changes that we make to the spreadsheets, if needed. @natschja let us know if we should do that, and then feel free to close this issue.
