### ISSUE TITLE
Medication Codes Value Set 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#20]
For mapping medications that are currently being taken, some of the medications are already in the FHIR medication codes value set.  These are currently from SNOMED.  

Possible Options (Need to determine if these are technically feasible):  
1.  Do we want a FHIR extension with ONLY the codes in the WHO DD?  The issue with this is that we are limiting the choices to the ones on the list in the DD.  (Need to verify that) 
2.  Do we want to extend the list to have the drugs that are on the WHO list + the ones that are already described in FHIR.  

Note that the medication questions in the WHO DD are currently specified for "Determine if client is taking certain anticonvulsants, antimicrobials, and antiretrovirals, which may affect their medical eligibility, as well as if client is on antiretroviral therapy, pre-exposure prophylaxis, etc. "

@natschja @brynrhodes @terrycullen @jamlung-ri

**Comment by natschja** [comment]
Are there medications in any other terminologies? I think this would be a good question to discuss with Garrett (don't think he has a GitHub account linked yet). 

My initial thoughts are that on the one hand, it's better to be more inclusive and have all the medications possible here since they're already included in the FHIR value set. However, I'm not sure if the inclusion of the extra medications are indicative of WHO "recommending" them or saying that they should be included; whereas the list in the accelerator kits reflect the "minimum" requirement. 

What are the technical implications of this @brynrhodes ?

**Comment by brynrhodes** [comment]
When we say "FHIR medication codes value set", what value set are we referring to here? I'd be very surprised if the FHIR base specification provided a medication value set that was anything more than an example binding.

**Comment by jamlung-ri** [comment]
@brynrhodes I think you're right, and I think what we mean here is about binding to the SNOMED CT Medication Codes. So Jennifer's option #1 would mean that there is a Required value set binding to the medications that WHO listed out for us. #2, on the other hand, would mean that any SNOMED or RxNorm code is valid, and we have simply mapped WHO's specified medication list to their respective SNOMED/RxNorm codes.

**Comment by brynrhodes** [comment]
I see, that makes sense. I would suggest option 1 makes more sense for an implementation guide where we are trying to specify the minimum data set, the less optionality the better, because we're trying to be as precise as possible about what we mean.

**Comment by jennifershivers** [comment]
This has been done suggesting the minimum data set and mapped to FHIR resource MedicationStatement.medication[x]
