### ISSUE TITLE
1491 - Diabetes >20 years duration

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#74]
How should we model "Diabetes >20 years duration"? @bmamlin notes that 'There's a "long duration" SNOMED-CT term 260384008 that could be combined with dx like diabetes or vascular disease'. Does this make clinical sense to do this? If so, how can we note that this SNOMED code must be used in combination with another code?

Reference: [ID 1491](https://docs.google.com/spreadsheets/d/1qwteFzcSByOKdW_k1TVUDQe5WxAukRafGeEVmcrn6us)

**Comment by bmamlin** [comment]
This comes down to pre-coordination vs. post-coordination, which [Lauren described well here](https://wiki.openmrs.org/x/SpIvAg).

Pre-coordination involves creating new concepts for these specific questions. Harder to do when working with international standards, but easier to use.

Post-coordination means combining concepts to communicate something. It may be easier to accomplish if you don't have to create new concepts, but often harder to use.

My 2¢ would be to request new concepts for these, since relying on post-coordination will narrow the list of systems that can use the information significantly... perhaps to zero. 😉

**Comment by terrycullen** [comment]
'Long duration' is ambiguous at best. I agree that pre-coordination is critical; however, I also think that one of the issues is how much pre-coordination is needed and why. So, the CDS use case matters (for instance, I dont know how critical knowing that someone has diabetes more than 20 years is in most CDS). We may create a Tower of Babel here

**Comment by brynrhodes** [comment]
Another alternative is to model this is an "inference". We are still in the process of figuring out what that would really look like, but this might be a good case to use to prove that out. The idea is that the Data Element would be defined as the result of an expression; exists ([Condition: Diabetes] C where C.onset more than 20 years before Today()).

A distinct advantage of expressing it this way is that it makes it very clear that this concept is relying on "the moving point now".

**Comment by jamlung-ri** [comment]
Based on this discussion and our discussion at the meeting today, we will move forward with Bryn's recommendation. We will however need to discuss how an inference can be reflected in the data dictionary spreadsheet (see [ticket 77)](https://github.com/who-int/Data-Dictionary-Mapping/issues/77).

**Comment by jennifershivers** [comment]
Calculation from
