### ISSUE TITLE
Possible extension - date of birth unknown 

### ISSUE THREAD

**Issue by jennifershivers** [WorldHealthOrganization/smart-data-dictionary#9]
1245 - Date of birth unknown is not in the FHIR standard 

Do we want to look for terminology or how will we extend?

**Comment by jamlung-ri** [comment]
My thought is that "Date of birth unknown" is a user interface (UI) element, rather than something that should be mapped to FHIR. I would think that its purpose in the UI is to allow a user to not enter the date of birth in case it is unknown, ensuring that the date of birth question is not mistakenly skipped. In FHIR, the date of birth can already be empty (since its Cardinality = 0..1), so I don't believe an extension to FHIR is needed.

**Comment by jennifershivers** [comment]
Recommendation:  
"Date of birth unknown" is a user interface (UI) element.  We believe that the purpose in the UI is to allow a user to not enter the date of birth in case it is unknown, ensuring that the date of birth question is not mistakenly skipped. In FHIR, the date of birth can already be empty (since its Cardinality = 0..1)  @natschja
