### ISSUE TITLE
Consolidate Input Options for "Reason for No Contraceptive Method"

### ISSUE THREAD

**Issue by jamlung-ri** [WorldHealthOrganization/smart-data-dictionary#90]
There are two sets of similar input options that relate to a reason for not having a contraceptive method, but there are also some distinctions between the two. Is there an issue with consolidating these input options into a single value set, or should they be left as separate value sets?

Reference: 

- ID 1319 - "Reason for no contraceptive method - Reported at intake" and its input options
   -   (similar to number 1 below)Sexual abstinence    
   -   Side effects from contraception
   -   Currently pregnant
   -   (both lists) Same sex partner    
   -   (both lists) Other    
   -   (both lists) Out of stock
   -   (both lists) Sterile for non-contraceptive reasons    
   -   (both lists) Seeking pregnancy   
- ID 1701 - "Reason for no method at exit" and its input options
   -   (similar to number 1 above) Voluntarily refrains from sexual intercourse
   -   Client choice to not use contraception
   -   (both lists) Same sex partner    
   -   (both lists) No method for other reasons
   -   (both lists) Out of stock
   -   (both lists) Sterile for non-contraceptive reasons    
   -   (both lists) Seeking pregnancy

**Comment by jennifershivers** [comment]
Recommendation:  Combine answer set into a single comprehensive list.  @natschja - please advise.

**Comment by natschja** [comment]
I've updated both of these lists actually - the "Reason for no method at exit" is incomplete and there are overlaps but not complete overlaps. Will send an update.

**Comment by jennifershivers** [comment]
If they really are different, should we consider naming them "STI Reason for no contraception method" and "FP Reason for no contraception method"?
Another note - the UI doesn't have to list all of the options.

**Comment by jennifershivers** [comment]
Recommendation:  to create one comprehensive list and implementers can support appropriate options on appropriate UIs.

**Comment by natschja** [comment]
The no contraceptive method is not relevant to STIs so it would be inappropriate to split it that way. The reason there are two lists for "no contraceptive methods" is because at intake - we want to know why a woman is not currently using a contraceptive method, whereas at the outtake, we want to know why she left the counselling session without a contraceptive method. 

We can consolidate them - but would need to verify that the list could be the same. 

Currently the list at intake:
a.	Abstinence    
b.	Side effects of contraception
c.	Currently pregnant
d.	Same sex partner    
e.	Sterile for non-contraceptive reasons    
f.	Seeking pregnancy   
g.	Out of stock
h.	Reported failure of contraceptive methods
i.	Other (specify) 
List at outtake
j.	Chooses not to use
k.	Out of stock
l.	IUD Insertion not possible
m.	Other (specify)

**Comment by jennifershivers** [comment]
Ok we can put into two profiles one for intake and the other for outtake. Once we see this, in FHIR, it might help.
